STEPS = [
('1 · 准备域名', '还没有域名：打开 Spaceship，搜索并购买一个域名，完成邮箱验证。已有别人转来的域名：确认它已经出现在你自己的注册商账户中，且能修改名称服务器。域名注册需要付费，Cloudflare 的 Free 套餐可免费使用。', 'https://www.spaceship.com/domains/'),
('2 · 添加到 Cloudflare', '注册或登录 Cloudflare。选择“添加域 / Add a domain”→“连接域”。输入根域名，例如 example.com，不能填 hy2.example.com 或 https://。继续并选择 Free 免费套餐。导入 DNS 时核对现有记录；如果域名同时用作邮箱，保留 MX、SPF、DKIM、DMARC 等记录。旧 A 记录只有确认不再使用时才删除。', 'https://dash.cloudflare.com/'),
('3 · 修改名称服务器', 'Cloudflare 会给你两条专属 NS。复制当前页面显示的两条，不要套用别人的。打开注册商的域名管理→名称服务器 / Nameservers→自定义，将旧 NS 替换成这两条并保存。Spaceship：域名管理器→选中域名→名称服务器和 DNS→更改。若 DNSSEC 已开启，先在注册商关闭并移除旧 DS，激活后可重新配置。', 'https://www.spaceship.com/zh/application/domain-list-application/'),
('4 · 等待激活', '回到 Cloudflare 域名概述，点击检查名称服务器（如果有）。等待状态变成 Active / 已激活。缓存传播无法由软件强行加速。期间可完成其余设置。已修改 NS 但长时间未激活时，核对拼写、是否只剩分配的两条 NS，以及是否残留旧 DNSSEC / DS。', 'https://developers.cloudflare.com/dns/zone-setups/full-setup/setup/'),
('5 · 添加访问域名解析', '进入 Cloudflare→该域名→DNS→记录→添加记录。类型 A，IPv4 地址填写当前 VPS 地址，TTL 自动。名称例如 node，得到 node.example.com，填入软件的访问域名。关闭小橙云，代理状态为“仅 DNS”的灰云。不要保留指向其他服务器的同名 A 记录；没有配置 IPv6 时删除不适用的同名 AAAA。保存后等待解析生效，点击软件“检查域名解析”。灰云只做解析，不改变 CN2 或其他 VPS 线路。没有域名时面板使用 IP 链接，无需 DNS。', 'https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/'),
('6 · 证书验证端口', '勾选“配置本机端口规则”后，软件通过 SSH 配置 TCP 80，用于申请证书和后续续期。若端口已能从外部访问，无需再去服务商后台设置。证书验证失败时先检查解析、端口占用、本机防火墙和 CAA；若服务商外部防火墙阻拦，再按实际服务商后台添加入站 TCP 80，来源 0.0.0.0/0，保存并绑定此 VPS。保留规则用于续期。TCP 80 仅在证书验证时临时监听，空闲时不用于判断节点连通性。若已被网站占用，软件提示冲突，不会停止已有服务。', 'https://letsencrypt.org/docs/challenge-types/#http-01-challenge'),
('7 · 只填域名并签发证书', '在部署参数选择“域名证书 · 自动申请”，只填写你的访问域名，点击“检查域名解析”，确认设置后开始部署。软件通过 TCP 80 完成 HTTP 验证，签发证书后自动为面板启用 HTTPS；启用 HY2 时共用该证书。仅部署 VLESS REALITY 时，证书用于面板，不改变 VLESS 线路或协议。证书每天自动检查续期。已有服务器可点击“给现有面板 / HY2 应用域名证书”，无需重新部署节点。解析匹配不代表 TCP 80 已放行；验证失败时核对安全组、服务器防火墙、端口占用和 CAA 限制。', 'https://letsencrypt.org/docs/challenge-types/#http-01-challenge'),
('8 · 自动验证与连接排查', '软件先通过 SSH 配置本机规则，再自动测试 VLESS / HY2 的实际 HTTPS 流量和公网面板入口。全部通过时不弹安全组提示，直接导入节点即可。“节点与端口”显示结果，可点击“重新验证节点与面板”。未通过时先检查服务监听、节点配置、本机防火墙、域名和当前网络；超时不能证明安全组阻拦。只有外部防火墙阻拦时才按实际服务商后台添加入站规则：VLESS 用 TCP，HY2 用 UDP，面板用 TCP；端口按结果清单，保留当前 SSH 规则。HY2 必须用协议客户端验证，不能只发送 UDP 数据。当前电脑通过不保证所有网络都通过，请在其他电脑验证面板链接。无域名为 HTTP IP 链接，登录信息不加密；域名证书使用 HTTPS。', 'https://github.com/Mr-Lee-951219/vps-one-click-deployer/blob/main/docs/user-guide.md'),
]
