STEPS = [
('1 · 准备域名', '还没有域名：打开 Spaceship，搜索并购买一个域名，完成邮箱验证。已有别人转来的域名：确认它已经出现在你自己的注册商账户中，且能修改名称服务器。域名注册需要付费，Cloudflare 的 Free 套餐可免费使用。', 'https://www.spaceship.com/domains/'),
('2 · 添加到 Cloudflare', '注册或登录 Cloudflare。选择“添加域 / Add a domain”→“连接域”。输入根域名，例如 example.com，不能填 hy2.example.com 或 https://。继续并选择 Free 免费套餐。导入 DNS 时核对现有记录；如果域名同时用作邮箱，保留 MX、SPF、DKIM、DMARC 等记录。旧 A 记录只有确认不再使用时才删除。', 'https://dash.cloudflare.com/'),
('3 · 修改名称服务器', 'Cloudflare 会给你两条专属 NS。复制当前页面显示的两条，不要套用别人的。打开注册商的域名管理→名称服务器 / Nameservers→自定义，将旧 NS 替换成这两条并保存。Spaceship：域名管理器→选中域名→名称服务器和 DNS→更改。若 DNSSEC 已开启，先在注册商关闭并移除旧 DS，激活后可重新配置。', 'https://www.spaceship.com/zh/application/domain-list-application/'),
('4 · 等待激活', '回到 Cloudflare 域名概述，点击检查名称服务器（如果有）。等待状态变成 Active / 已激活。缓存传播无法由软件强行加速。期间可完成其余设置。已修改 NS 但长时间未激活时，核对拼写、是否只剩分配的两条 NS，以及是否残留旧 DNSSEC / DS。', 'https://developers.cloudflare.com/dns/zone-setups/full-setup/setup/'),
('5 · 添加访问域名解析', '进入 Cloudflare→该域名→DNS→记录→添加记录。类型 A，IPv4 地址填写当前 VPS 地址，TTL 自动。名称例如 node，得到 node.example.com，填入软件的访问域名。关闭小橙云，代理状态为“仅 DNS”的灰云。不要保留指向其他服务器的同名 A 记录；没有配置 IPv6 时删除不适用的同名 AAAA。保存后等待解析生效，点击软件“检查域名解析”。灰云只做解析，不改变 CN2 或其他 VPS 线路。没有域名时面板使用 IP 链接，无需 DNS。', 'https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/'),
('6 · 提前放行证书验证端口', '在 RakSmart 客户中心打开对应 VPS 的安全组→创建规则：远程 IP 填 0.0.0.0/0，方向选入站，协议选 TCP，最小端口和最大端口都填 80。保存并绑定到这台 VPS。服务器本机防火墙也需允许 TCP 80，软件在启用本机规则时会配置。该端口用于申请证书和后续自动续期，需要持续保留。若 TCP 80 已被网站服务占用，软件会提示冲突，不会停止已有服务。证书验证使用 TCP 80，与面板和节点的随机端口分别配置。', 'https://billing.raksmart.com/whmcs/index.php?rp=/knowledgebase/1021/安全组.html'),
('7 · 只填域名并签发证书', '在部署参数选择“域名证书 · 自动申请”，只填写你的访问域名，点击“检查域名解析”，确认设置后开始部署。软件通过 TCP 80 完成 HTTP 验证，签发证书后自动为面板启用 HTTPS；启用 HY2 时共用该证书。仅部署 VLESS REALITY 时，证书用于面板，不改变 VLESS 线路或协议。证书每天自动检查续期。已有服务器可点击“给现有面板 / HY2 应用域名证书”，无需重新部署节点。解析匹配不代表 TCP 80 已放行；验证失败时核对安全组、服务器防火墙、端口占用和 CAA 限制。', 'https://letsencrypt.org/docs/challenge-types/#http-01-challenge'),
('8 · 开放实际端口并测试', '打开 RakSmart 客户中心→产品管理 / 我的服务→对应 VPS→安全组。选择入站，按结果清单逐条添加：VLESS 用 TCP，HY2 用 UDP，管理面板用 TCP；最小和最大端口都填实际端口，来源 0.0.0.0/0。保留当前 SSH 的 TCP 规则。公网云产品的入口可能为“我的服务→公有云→安全组”。规则保存并绑定后测试节点，并在另一台电脑浏览器打开部署结果的面板链接，用面板账号密码登录。无域名使用 HTTP IP 链接，登录信息不加密；已签发域名证书使用 HTTPS。', 'https://billing.raksmart.com/whmcs/index.php?rp=/knowledgebase/1021/安全组.html'),
]
